version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: kanban-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanban
    volumes:
      - postgres_data:/var/lib/postgresql/data
    platform: linux/arm64 # For M1 Macs

volumes:
  postgres_data:
